[package]
name = "imprev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.88.1"
libc = "*"
term_size = "*"
signal-hook = "0.3"
